/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n\t\t\t\tquery AccountOrdersPageOrders($userId: UUID!, $page: Int!, $pageSize: Int!) {\n\t\t\t\t\tuserOrders(userId: $userId, page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tnumber\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AccountOrdersPageOrdersDocument,
    "\n\t\t\t\tquery AccountOrdersPageOrder($orderId: UUID!) {\n\t\t\t\t\tuserOrder(orderId: $orderId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AccountOrdersPageOrderDocument,
    "\n\t\t\t\tquery AdminOrdersPageOrders($page: Int!, $pageSize: Int!) {\n\t\t\t\t\torders(page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminOrdersPageOrdersDocument,
    "\n\t\t\t\tquery AdminOrdersPageOrder($orderId: UUID!) {\n\t\t\t\t\torder(id: $orderId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminOrdersPageOrderDocument,
    "\n\t\t\t\tmutation AdminOrdersPageUpdateOrder($input: UpdateOrderInput!) {\n\t\t\t\t\tupdateOrder(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminOrdersPageUpdateOrderDocument,
    "\n\t\t\t\tquery AdminProductCatalogPageProducts($page: Int!, $pageSize: Int!) {\n\t\t\t\t\tcatalogProducts(page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductCatalogPageProductsDocument,
    "\n\t\t\t\tquery AdminProductPageProduct($id: UUID!) {\n\t\t\t\t\tproduct(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tgroup {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tsubCategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\topinionCount\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstartDate\n\t\t\t\t\t\t\tendDate\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tisEnabled\n\t\t\t\t\t\t}\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductPageProductDocument,
    "\n\t\t\t\tquery AdminProductPageProductHierarchy {\n\t\t\t\t\tproductHierarchy {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductPageProductHierarchyDocument,
    "\n\t\t\t\tquery AdminProductPageAttributesDefinitions($groupId: Int, $categoryId: Int, $subCategoryId: Int) {\n\t\t\t\t\tattributesDefinitions(groupId: $groupId, categoryId: $categoryId, subCategoryId: $subCategoryId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tisRequired\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tisFilterable\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductPageAttributesDefinitionsDocument,
    "\n\t\t\t\tmutation AdminProductPageCreateOrUpdateProduct($input: CreateOrUpdateProductInput!) {\n\t\t\t\t\tcreateOrUpdateProduct(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductPageCreateOrUpdateProductDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageProductHierarchy {\n\t\t\t\t\tproductHierarchy {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageProductHierarchyDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageGroup($id: Int!) {\n\t\t\t\t\tgroup(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageGroupDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageCategory($id: Int!) {\n\t\t\t\t\tcategory(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tgroupId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageCategoryDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageSubCategory($id: Int!) {\n\t\t\t\t\tsubCategory(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tcategoryId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageSubCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateGroup($input: CreateOrUpdateGroupInput!) {\n\t\t\t\t\tcreateOrUpdateGroup(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageCreateOrUpdateGroupDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteGroup($id: Int!) {\n\t\t\t\t\tdeleteGroup(id: $id)\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageDeleteGroupDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateCategory($input: CreateOrUpdateCategoryInput!) {\n\t\t\t\t\tcreateOrUpdateCategory(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageCreateOrUpdateCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteCategory($id: Int!) {\n\t\t\t\t\tdeleteCategory(id: $id)\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageDeleteCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateSubCategory($input: CreateOrUpdateSubCategoryInput!) {\n\t\t\t\t\tcreateOrUpdateSubCategory(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tcategoryId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageCreateOrUpdateSubCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteSubCategory($id: Int!) {\n\t\t\t\t\tdeleteSubCategory(id: $id)\n\t\t\t\t}\n\t\t\t": typeof types.AdminProductHierarchyPageDeleteSubCategoryDocument,
    "\n\t\t\t\tmutation AuthPageRegister($input: RegisterInput!) {\n\t\t\t\t\tregisterUser(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AuthPageRegisterDocument,
    "\n\t\t\t\tmutation AuthPageLogin($input: LoginInput!) {\n\t\t\t\t\tloginUser(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AuthPageLoginDocument,
    "\n\t\t\t\tmutation AuthPageRefreshToken($input: RefreshTokenInput!) {\n\t\t\t\t\trefreshToken(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.AuthPageRefreshTokenDocument,
    "\n\t\t\t\tmutation AuthPageLogout {\n\t\t\t\t\tlogoutUser\n\t\t\t\t}\n\t\t\t": typeof types.AuthPageLogoutDocument,
    "\n\t\t\t\tquery CartPageCart($userId: UUID!) {\n\t\t\t\t\tcart(userId: $userId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\ttotalQuantity\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.CartPageCartDocument,
    "\n\t\t\t\tmutation CartPageValidateCart($input: ValidateCartInput!) {\n\t\t\t\t\tvalidateCart(input: $input) {\n\t\t\t\t\t\tcart {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\ttotalQuantity\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\terrors\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.CartPageValidateCartDocument,
    "\n\t\t\t\tquery CartPageRecipients($userId: UUID!) {\n\t\t\t\t\trecipients(userId: $userId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfirstName\n\t\t\t\t\t\tsurname\n\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\tstreet\n\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\tcity\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.CartPageRecipientsDocument,
    "\n\t\t\t\tmutation CartPageCreateOrUpdateRecipient($input: CreateOrUpdateRecipientInput!) {\n\t\t\t\t\tcreateOrUpdateRecipient(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfirstName\n\t\t\t\t\t\tsurname\n\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\tstreet\n\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\tcity\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.CartPageCreateOrUpdateRecipientDocument,
    "\n\t\t\t\tmutation CartPageDeleteRecipient($recipientId: UUID!, $userId: UUID!) {\n\t\t\t\t\tdeleteRecipient(recipientId: $recipientId, userId: $userId)\n\t\t\t\t}\n\t\t\t": typeof types.CartPageDeleteRecipientDocument,
    "\n\t\t\t\tmutation CartPageCreateOrder($input: CreateOrderInput!) {\n\t\t\t\t\tcreateOrder(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tstatus\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.CartPageCreateOrderDocument,
    "\n\t\t\t\tquery LayoutMenu {\n\t\t\t\t\tmenu {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.LayoutMenuDocument,
    "\n\t\t\t\tquery ProductPageProduct($id: UUID!) {\n\t\t\t\t\tproduct(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tgroup {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tsubCategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\topinionCount\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstartDate\n\t\t\t\t\t\t\tendDate\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tisEnabled\n\t\t\t\t\t\t}\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.ProductPageProductDocument,
    "\n\t\t\t\tquery ProductPageOpinions($productId: UUID!, $page: Int!, $pageSize: Int!, $rating: Int) {\n\t\t\t\t\tproductOpinions(productId: $productId, page: $page, pageSize: $pageSize, rating: $rating) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tcontent\n\t\t\t\t\t\t\trating\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t\tauthorDisplayName\n\t\t\t\t\t\t\tuserReaction\n\t\t\t\t\t\t\tlikesCount\n\t\t\t\t\t\t\tdislikesCount\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.ProductPageOpinionsDocument,
    "\n\t\t\t\tquery ProductPageOpinionsStats($productId: UUID!) {\n\t\t\t\t\tproductOpinionsStats(productId: $productId) {\n\t\t\t\t\t\trating\n\t\t\t\t\t\tcount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.ProductPageOpinionsStatsDocument,
    "\n\t\t\t\tmutation ProductPageCreateOpinionReaction($input: CreateOpinionReactionInput!) {\n\t\t\t\t\tcreateOpinionReaction(input: $input) {\n\t\t\t\t\t\tuserReaction\n\t\t\t\t\t\tlikesCount\n\t\t\t\t\t\tdislikesCount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.ProductPageCreateOpinionReactionDocument,
    "\n\t\t\t\tmutation ProductPageCreateOpinion($input: CreateOpinionInput!) {\n\t\t\t\t\tcreateOpinion(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tcontent\n\t\t\t\t\t\trating\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tauthorDisplayName\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.ProductPageCreateOpinionDocument,
    "\n\t\t\t\tquery ProductPageSimilarProducts($productId: UUID!, $limit: Int) {\n\t\t\t\t\tsimilarProducts(productId: $productId, limit: $limit) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.ProductPageSimilarProductsDocument,
    "\n\t\t\t\tquery SearchPageProducts($input: GetSearchProductsInput!) {\n\t\t\t\t\tsearchProducts(input: $input) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\t\topinionCount\n\t\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.SearchPageProductsDocument,
    "\n\t\t\t\tquery SeachPageFilters($groupId: Int, $categoryId: Int, $subCategoryId: Int) {\n\t\t\t\t\tproductFilters(groupId: $groupId, categoryId: $categoryId, subCategoryId: $subCategoryId) {\n\t\t\t\t\t\tattributeDefinitionId\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tname\n\t\t\t\t\t\tvalues\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.SeachPageFiltersDocument,
    "\n\t\t\t\tquery SeachPageProductHierarchy {\n\t\t\t\t\tmenu {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.SeachPageProductHierarchyDocument,
    "\n\t\t\t\t\tquery RootPageBestsellerProducts($limit: Int) {\n\t\t\t\t\t\tbestsellerProducts(limit: $limit) {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t": typeof types.RootPageBestsellerProductsDocument,
    "\n\t\t\t\t\tquery RootPageFeaturedProducts($limit: Int) {\n\t\t\t\t\t\tfeaturedProducts(limit: $limit) {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t": typeof types.RootPageFeaturedProductsDocument,
    "\n\t\t\t\tquery RootPagePromotionHightlight {\n\t\t\t\t\tpromotionHighlightProduct {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": typeof types.RootPagePromotionHightlightDocument,
};
const documents: Documents = {
    "\n\t\t\t\tquery AccountOrdersPageOrders($userId: UUID!, $page: Int!, $pageSize: Int!) {\n\t\t\t\t\tuserOrders(userId: $userId, page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tnumber\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AccountOrdersPageOrdersDocument,
    "\n\t\t\t\tquery AccountOrdersPageOrder($orderId: UUID!) {\n\t\t\t\t\tuserOrder(orderId: $orderId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AccountOrdersPageOrderDocument,
    "\n\t\t\t\tquery AdminOrdersPageOrders($page: Int!, $pageSize: Int!) {\n\t\t\t\t\torders(page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminOrdersPageOrdersDocument,
    "\n\t\t\t\tquery AdminOrdersPageOrder($orderId: UUID!) {\n\t\t\t\t\torder(id: $orderId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminOrdersPageOrderDocument,
    "\n\t\t\t\tmutation AdminOrdersPageUpdateOrder($input: UpdateOrderInput!) {\n\t\t\t\t\tupdateOrder(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminOrdersPageUpdateOrderDocument,
    "\n\t\t\t\tquery AdminProductCatalogPageProducts($page: Int!, $pageSize: Int!) {\n\t\t\t\t\tcatalogProducts(page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductCatalogPageProductsDocument,
    "\n\t\t\t\tquery AdminProductPageProduct($id: UUID!) {\n\t\t\t\t\tproduct(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tgroup {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tsubCategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\topinionCount\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstartDate\n\t\t\t\t\t\t\tendDate\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tisEnabled\n\t\t\t\t\t\t}\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductPageProductDocument,
    "\n\t\t\t\tquery AdminProductPageProductHierarchy {\n\t\t\t\t\tproductHierarchy {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductPageProductHierarchyDocument,
    "\n\t\t\t\tquery AdminProductPageAttributesDefinitions($groupId: Int, $categoryId: Int, $subCategoryId: Int) {\n\t\t\t\t\tattributesDefinitions(groupId: $groupId, categoryId: $categoryId, subCategoryId: $subCategoryId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tisRequired\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tisFilterable\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductPageAttributesDefinitionsDocument,
    "\n\t\t\t\tmutation AdminProductPageCreateOrUpdateProduct($input: CreateOrUpdateProductInput!) {\n\t\t\t\t\tcreateOrUpdateProduct(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductPageCreateOrUpdateProductDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageProductHierarchy {\n\t\t\t\t\tproductHierarchy {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageProductHierarchyDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageGroup($id: Int!) {\n\t\t\t\t\tgroup(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageGroupDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageCategory($id: Int!) {\n\t\t\t\t\tcategory(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tgroupId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageCategoryDocument,
    "\n\t\t\t\tquery AdminProductHierarchyPageSubCategory($id: Int!) {\n\t\t\t\t\tsubCategory(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tcategoryId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageSubCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateGroup($input: CreateOrUpdateGroupInput!) {\n\t\t\t\t\tcreateOrUpdateGroup(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageCreateOrUpdateGroupDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteGroup($id: Int!) {\n\t\t\t\t\tdeleteGroup(id: $id)\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageDeleteGroupDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateCategory($input: CreateOrUpdateCategoryInput!) {\n\t\t\t\t\tcreateOrUpdateCategory(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageCreateOrUpdateCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteCategory($id: Int!) {\n\t\t\t\t\tdeleteCategory(id: $id)\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageDeleteCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateSubCategory($input: CreateOrUpdateSubCategoryInput!) {\n\t\t\t\t\tcreateOrUpdateSubCategory(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tcategoryId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageCreateOrUpdateSubCategoryDocument,
    "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteSubCategory($id: Int!) {\n\t\t\t\t\tdeleteSubCategory(id: $id)\n\t\t\t\t}\n\t\t\t": types.AdminProductHierarchyPageDeleteSubCategoryDocument,
    "\n\t\t\t\tmutation AuthPageRegister($input: RegisterInput!) {\n\t\t\t\t\tregisterUser(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AuthPageRegisterDocument,
    "\n\t\t\t\tmutation AuthPageLogin($input: LoginInput!) {\n\t\t\t\t\tloginUser(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AuthPageLoginDocument,
    "\n\t\t\t\tmutation AuthPageRefreshToken($input: RefreshTokenInput!) {\n\t\t\t\t\trefreshToken(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.AuthPageRefreshTokenDocument,
    "\n\t\t\t\tmutation AuthPageLogout {\n\t\t\t\t\tlogoutUser\n\t\t\t\t}\n\t\t\t": types.AuthPageLogoutDocument,
    "\n\t\t\t\tquery CartPageCart($userId: UUID!) {\n\t\t\t\t\tcart(userId: $userId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\ttotalQuantity\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.CartPageCartDocument,
    "\n\t\t\t\tmutation CartPageValidateCart($input: ValidateCartInput!) {\n\t\t\t\t\tvalidateCart(input: $input) {\n\t\t\t\t\t\tcart {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\ttotalQuantity\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\terrors\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.CartPageValidateCartDocument,
    "\n\t\t\t\tquery CartPageRecipients($userId: UUID!) {\n\t\t\t\t\trecipients(userId: $userId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfirstName\n\t\t\t\t\t\tsurname\n\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\tstreet\n\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\tcity\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.CartPageRecipientsDocument,
    "\n\t\t\t\tmutation CartPageCreateOrUpdateRecipient($input: CreateOrUpdateRecipientInput!) {\n\t\t\t\t\tcreateOrUpdateRecipient(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfirstName\n\t\t\t\t\t\tsurname\n\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\tstreet\n\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\tcity\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.CartPageCreateOrUpdateRecipientDocument,
    "\n\t\t\t\tmutation CartPageDeleteRecipient($recipientId: UUID!, $userId: UUID!) {\n\t\t\t\t\tdeleteRecipient(recipientId: $recipientId, userId: $userId)\n\t\t\t\t}\n\t\t\t": types.CartPageDeleteRecipientDocument,
    "\n\t\t\t\tmutation CartPageCreateOrder($input: CreateOrderInput!) {\n\t\t\t\t\tcreateOrder(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tstatus\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.CartPageCreateOrderDocument,
    "\n\t\t\t\tquery LayoutMenu {\n\t\t\t\t\tmenu {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.LayoutMenuDocument,
    "\n\t\t\t\tquery ProductPageProduct($id: UUID!) {\n\t\t\t\t\tproduct(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tgroup {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tsubCategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\topinionCount\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstartDate\n\t\t\t\t\t\t\tendDate\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tisEnabled\n\t\t\t\t\t\t}\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.ProductPageProductDocument,
    "\n\t\t\t\tquery ProductPageOpinions($productId: UUID!, $page: Int!, $pageSize: Int!, $rating: Int) {\n\t\t\t\t\tproductOpinions(productId: $productId, page: $page, pageSize: $pageSize, rating: $rating) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tcontent\n\t\t\t\t\t\t\trating\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t\tauthorDisplayName\n\t\t\t\t\t\t\tuserReaction\n\t\t\t\t\t\t\tlikesCount\n\t\t\t\t\t\t\tdislikesCount\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.ProductPageOpinionsDocument,
    "\n\t\t\t\tquery ProductPageOpinionsStats($productId: UUID!) {\n\t\t\t\t\tproductOpinionsStats(productId: $productId) {\n\t\t\t\t\t\trating\n\t\t\t\t\t\tcount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.ProductPageOpinionsStatsDocument,
    "\n\t\t\t\tmutation ProductPageCreateOpinionReaction($input: CreateOpinionReactionInput!) {\n\t\t\t\t\tcreateOpinionReaction(input: $input) {\n\t\t\t\t\t\tuserReaction\n\t\t\t\t\t\tlikesCount\n\t\t\t\t\t\tdislikesCount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.ProductPageCreateOpinionReactionDocument,
    "\n\t\t\t\tmutation ProductPageCreateOpinion($input: CreateOpinionInput!) {\n\t\t\t\t\tcreateOpinion(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tcontent\n\t\t\t\t\t\trating\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tauthorDisplayName\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.ProductPageCreateOpinionDocument,
    "\n\t\t\t\tquery ProductPageSimilarProducts($productId: UUID!, $limit: Int) {\n\t\t\t\t\tsimilarProducts(productId: $productId, limit: $limit) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.ProductPageSimilarProductsDocument,
    "\n\t\t\t\tquery SearchPageProducts($input: GetSearchProductsInput!) {\n\t\t\t\t\tsearchProducts(input: $input) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\t\topinionCount\n\t\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.SearchPageProductsDocument,
    "\n\t\t\t\tquery SeachPageFilters($groupId: Int, $categoryId: Int, $subCategoryId: Int) {\n\t\t\t\t\tproductFilters(groupId: $groupId, categoryId: $categoryId, subCategoryId: $subCategoryId) {\n\t\t\t\t\t\tattributeDefinitionId\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tname\n\t\t\t\t\t\tvalues\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.SeachPageFiltersDocument,
    "\n\t\t\t\tquery SeachPageProductHierarchy {\n\t\t\t\t\tmenu {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.SeachPageProductHierarchyDocument,
    "\n\t\t\t\t\tquery RootPageBestsellerProducts($limit: Int) {\n\t\t\t\t\t\tbestsellerProducts(limit: $limit) {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t": types.RootPageBestsellerProductsDocument,
    "\n\t\t\t\t\tquery RootPageFeaturedProducts($limit: Int) {\n\t\t\t\t\t\tfeaturedProducts(limit: $limit) {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t": types.RootPageFeaturedProductsDocument,
    "\n\t\t\t\tquery RootPagePromotionHightlight {\n\t\t\t\t\tpromotionHighlightProduct {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t": types.RootPagePromotionHightlightDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AccountOrdersPageOrders($userId: UUID!, $page: Int!, $pageSize: Int!) {\n\t\t\t\t\tuserOrders(userId: $userId, page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tnumber\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AccountOrdersPageOrdersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AccountOrdersPageOrder($orderId: UUID!) {\n\t\t\t\t\tuserOrder(orderId: $orderId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AccountOrdersPageOrderDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminOrdersPageOrders($page: Int!, $pageSize: Int!) {\n\t\t\t\t\torders(page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminOrdersPageOrdersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminOrdersPageOrder($orderId: UUID!) {\n\t\t\t\t\torder(id: $orderId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminOrdersPageOrderDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminOrdersPageUpdateOrder($input: UpdateOrderInput!) {\n\t\t\t\t\tupdateOrder(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tupdatedAt\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpayment {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tpaidAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\tdelivery {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tmethod\n\t\t\t\t\t\t\tcost {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\ttrackingNumber\n\t\t\t\t\t\t\tshippedAt\n\t\t\t\t\t\t\tdeliveredAt\n\t\t\t\t\t\t}\n\t\t\t\t\t\trecipient {\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tfirstName\n\t\t\t\t\t\t\tsurname\n\t\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\t\tstreet\n\t\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\t\tcity\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminOrdersPageUpdateOrderDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductCatalogPageProducts($page: Int!, $pageSize: Int!) {\n\t\t\t\t\tcatalogProducts(page: $page, pageSize: $pageSize) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductCatalogPageProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductPageProduct($id: UUID!) {\n\t\t\t\t\tproduct(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tgroup {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tsubCategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\topinionCount\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstartDate\n\t\t\t\t\t\t\tendDate\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tisEnabled\n\t\t\t\t\t\t}\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductPageProductDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductPageProductHierarchy {\n\t\t\t\t\tproductHierarchy {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductPageProductHierarchyDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductPageAttributesDefinitions($groupId: Int, $categoryId: Int, $subCategoryId: Int) {\n\t\t\t\t\tattributesDefinitions(groupId: $groupId, categoryId: $categoryId, subCategoryId: $subCategoryId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tisRequired\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tisFilterable\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductPageAttributesDefinitionsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminProductPageCreateOrUpdateProduct($input: CreateOrUpdateProductInput!) {\n\t\t\t\t\tcreateOrUpdateProduct(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductPageCreateOrUpdateProductDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductHierarchyPageProductHierarchy {\n\t\t\t\t\tproductHierarchy {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageProductHierarchyDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductHierarchyPageGroup($id: Int!) {\n\t\t\t\t\tgroup(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageGroupDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductHierarchyPageCategory($id: Int!) {\n\t\t\t\t\tcategory(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tgroupId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery AdminProductHierarchyPageSubCategory($id: Int!) {\n\t\t\t\t\tsubCategory(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tcategoryId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageSubCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateGroup($input: CreateOrUpdateGroupInput!) {\n\t\t\t\t\tcreateOrUpdateGroup(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageCreateOrUpdateGroupDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteGroup($id: Int!) {\n\t\t\t\t\tdeleteGroup(id: $id)\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageDeleteGroupDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateCategory($input: CreateOrUpdateCategoryInput!) {\n\t\t\t\t\tcreateOrUpdateCategory(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageCreateOrUpdateCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteCategory($id: Int!) {\n\t\t\t\t\tdeleteCategory(id: $id)\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageDeleteCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminProductHierarchyPageCreateOrUpdateSubCategory($input: CreateOrUpdateSubCategoryInput!) {\n\t\t\t\t\tcreateOrUpdateSubCategory(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tactive\n\t\t\t\t\t\tdisplayOrder\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tmodifiedAt\n\t\t\t\t\t\tcategoryId\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\tisRequired\n\t\t\t\t\t\t\tisFilterable\n\t\t\t\t\t\t\tdescription\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageCreateOrUpdateSubCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AdminProductHierarchyPageDeleteSubCategory($id: Int!) {\n\t\t\t\t\tdeleteSubCategory(id: $id)\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AdminProductHierarchyPageDeleteSubCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AuthPageRegister($input: RegisterInput!) {\n\t\t\t\t\tregisterUser(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AuthPageRegisterDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AuthPageLogin($input: LoginInput!) {\n\t\t\t\t\tloginUser(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AuthPageLoginDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AuthPageRefreshToken($input: RefreshTokenInput!) {\n\t\t\t\t\trefreshToken(input: $input) {\n\t\t\t\t\t\tsuccess\n\t\t\t\t\t\tmessage\n\t\t\t\t\t\tuserId\n\t\t\t\t\t\ttoken\n\t\t\t\t\t\ttokenExpiry\n\t\t\t\t\t\trefreshToken\n\t\t\t\t\t\trefreshTokenExpiry\n\t\t\t\t\t\troles\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AuthPageRefreshTokenDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation AuthPageLogout {\n\t\t\t\t\tlogoutUser\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').AuthPageLogoutDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery CartPageCart($userId: UUID!) {\n\t\t\t\t\tcart(userId: $userId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\ttotalQuantity\n\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').CartPageCartDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation CartPageValidateCart($input: ValidateCartInput!) {\n\t\t\t\t\tvalidateCart(input: $input) {\n\t\t\t\t\t\tcart {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\ttotalQuantity\n\t\t\t\t\t\t\ttotalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tproducts {\n\t\t\t\t\t\t\t\tquantity\n\t\t\t\t\t\t\t\tproduct {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\terrors\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').CartPageValidateCartDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery CartPageRecipients($userId: UUID!) {\n\t\t\t\t\trecipients(userId: $userId) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfirstName\n\t\t\t\t\t\tsurname\n\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\tstreet\n\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\tcity\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').CartPageRecipientsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation CartPageCreateOrUpdateRecipient($input: CreateOrUpdateRecipientInput!) {\n\t\t\t\t\tcreateOrUpdateRecipient(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfirstName\n\t\t\t\t\t\tsurname\n\t\t\t\t\t\tcompanyName\n\t\t\t\t\t\ttaxIdentificationNumber\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tphoneNumber\n\t\t\t\t\t\tstreet\n\t\t\t\t\t\thouseNumber\n\t\t\t\t\t\tpostalCode\n\t\t\t\t\t\tcity\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').CartPageCreateOrUpdateRecipientDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation CartPageDeleteRecipient($recipientId: UUID!, $userId: UUID!) {\n\t\t\t\t\tdeleteRecipient(recipientId: $recipientId, userId: $userId)\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').CartPageDeleteRecipientDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation CartPageCreateOrder($input: CreateOrderInput!) {\n\t\t\t\t\tcreateOrder(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tstatus\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').CartPageCreateOrderDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery LayoutMenu {\n\t\t\t\t\tmenu {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').LayoutMenuDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery ProductPageProduct($id: UUID!) {\n\t\t\t\t\tproduct(id: $id) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tdescription\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tstatus\n\t\t\t\t\t\tgroup {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tcategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tsubCategory {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t}\n\t\t\t\t\t\tstockQuantity\n\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\topinionCount\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tstartDate\n\t\t\t\t\t\t\tendDate\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tisEnabled\n\t\t\t\t\t\t}\n\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').ProductPageProductDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery ProductPageOpinions($productId: UUID!, $page: Int!, $pageSize: Int!, $rating: Int) {\n\t\t\t\t\tproductOpinions(productId: $productId, page: $page, pageSize: $pageSize, rating: $rating) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tcontent\n\t\t\t\t\t\t\trating\n\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t\tauthorDisplayName\n\t\t\t\t\t\t\tuserReaction\n\t\t\t\t\t\t\tlikesCount\n\t\t\t\t\t\t\tdislikesCount\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').ProductPageOpinionsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery ProductPageOpinionsStats($productId: UUID!) {\n\t\t\t\t\tproductOpinionsStats(productId: $productId) {\n\t\t\t\t\t\trating\n\t\t\t\t\t\tcount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').ProductPageOpinionsStatsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation ProductPageCreateOpinionReaction($input: CreateOpinionReactionInput!) {\n\t\t\t\t\tcreateOpinionReaction(input: $input) {\n\t\t\t\t\t\tuserReaction\n\t\t\t\t\t\tlikesCount\n\t\t\t\t\t\tdislikesCount\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').ProductPageCreateOpinionReactionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tmutation ProductPageCreateOpinion($input: CreateOpinionInput!) {\n\t\t\t\t\tcreateOpinion(input: $input) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tcontent\n\t\t\t\t\t\trating\n\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\tauthorDisplayName\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').ProductPageCreateOpinionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery ProductPageSimilarProducts($productId: UUID!, $limit: Int) {\n\t\t\t\t\tsimilarProducts(productId: $productId, limit: $limit) {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tphotos\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').ProductPageSimilarProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery SearchPageProducts($input: GetSearchProductsInput!) {\n\t\t\t\t\tsearchProducts(input: $input) {\n\t\t\t\t\t\titems {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tstatus\n\t\t\t\t\t\t\taverageOpinionRating\n\t\t\t\t\t\t\topinionCount\n\t\t\t\t\t\t\tattributes {\n\t\t\t\t\t\t\t\tvalue\n\t\t\t\t\t\t\t\tisPrimary\n\t\t\t\t\t\t\t\tattributeDefinition {\n\t\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t\t\ttype\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tpage\n\t\t\t\t\t\tpageSize\n\t\t\t\t\t\ttotalPages\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').SearchPageProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery SeachPageFilters($groupId: Int, $categoryId: Int, $subCategoryId: Int) {\n\t\t\t\t\tproductFilters(groupId: $groupId, categoryId: $categoryId, subCategoryId: $subCategoryId) {\n\t\t\t\t\t\tattributeDefinitionId\n\t\t\t\t\t\ttype\n\t\t\t\t\t\tname\n\t\t\t\t\t\tvalues\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').SeachPageFiltersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery SeachPageProductHierarchy {\n\t\t\t\t\tmenu {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tphoto\n\t\t\t\t\t\ticon\n\t\t\t\t\t\tcategories {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tsubCategories {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').SeachPageProductHierarchyDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\t\tquery RootPageBestsellerProducts($limit: Int) {\n\t\t\t\t\t\tbestsellerProducts(limit: $limit) {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t"): typeof import('./graphql').RootPageBestsellerProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\t\tquery RootPageFeaturedProducts($limit: Int) {\n\t\t\t\t\t\tfeaturedProducts(limit: $limit) {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tname\n\t\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t"): typeof import('./graphql').RootPageFeaturedProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tquery RootPagePromotionHightlight {\n\t\t\t\t\tpromotionHighlightProduct {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tprice {\n\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t}\n\t\t\t\t\t\tmainPhoto\n\t\t\t\t\t\tpromotion {\n\t\t\t\t\t\t\tpromotionalPrice {\n\t\t\t\t\t\t\t\tamount\n\t\t\t\t\t\t\t\tcurrency\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t"): typeof import('./graphql').RootPagePromotionHightlightDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
