//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AttributeDefinitionCommand {
    id?: string | undefined;
    name?: string | undefined;
    type?: AttributeType;
    isRequired?: boolean;
    description?: string | undefined;
}

export interface AttributeDefinitionResult {
    id?: string;
    name?: string | undefined;
    type?: AttributeType;
    isRequired?: boolean;
    description?: string | undefined;
}

export enum AttributeType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export interface CreateOrUpdateCategoryCommand {
    id?: number | undefined;
    name?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    groupId?: number;
    attributes?: AttributeDefinitionCommand[] | undefined;
}

export interface CreateOrUpdateCategoryResult {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    groupId?: number | undefined;
    createdAt?: Date;
    modifiedAt?: Date;
    attributes?: AttributeDefinitionResult[] | undefined;
}

export interface CreateOrUpdateGroupCommand {
    id?: number | undefined;
    name?: string | undefined;
    icon?: string | undefined;
    photo?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    attributes?: AttributeDefinitionCommand[] | undefined;
}

export interface CreateOrUpdateGroupResult {
    id?: number;
    name?: string | undefined;
    icon?: string | undefined;
    photo?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    createdAt?: Date;
    modifiedAt?: Date;
    attributes?: AttributeDefinitionResult[] | undefined;
}

export interface CreateOrUpdateProductCommand {
    id?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    amount?: number;
    currency?: string | undefined;
    photos?: string[] | undefined;
    active?: boolean;
    stockQuantity?: number;
    status?: string | undefined;
    groupId?: number | undefined;
    categoryId?: number | undefined;
    subCategoryId?: number | undefined;
    attributes?: CreateOrUpdateProductCommandAttributeDefinitionValue[] | undefined;
}

export interface CreateOrUpdateProductCommandAttributeDefinitionValue {
    id?: string;
    value?: string | undefined;
    isPrimary?: boolean;
}

export interface CreateOrUpdateProductResult {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    amount?: number;
    currency?: string | undefined;
    photos?: string[] | undefined;
    status?: string | undefined;
    groupId?: number | undefined;
    categoryId?: number | undefined;
    subCategoryId?: number | undefined;
    attributes?: ProductAttributeResult[] | undefined;
}

export interface CreateOrUpdateSubCategoryCommand {
    id?: number | undefined;
    name?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    categoryId?: number;
    attributes?: AttributeDefinitionCommand[] | undefined;
}

export interface CreateOrUpdateSubCategoryResult {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    categoryId?: number | undefined;
    createdAt?: Date;
    modifiedAt?: Date;
    attributes?: AttributeDefinitionResult[] | undefined;
}

export interface GetAllProductHierarchyCategory {
    id?: number;
    name?: string | undefined;
    subCategories?: GetAllProductHierarchySubCategory[] | undefined;
}

export interface GetAllProductHierarchyGroup {
    id?: number;
    name?: string | undefined;
    photo?: string | undefined;
    icon?: string | undefined;
    categories?: GetAllProductHierarchyCategory[] | undefined;
}

export interface GetAllProductHierarchyResult {
    groups?: GetAllProductHierarchyGroup[] | undefined;
}

export interface GetAllProductHierarchySubCategory {
    id?: number;
    name?: string | undefined;
}

export interface GetAttributesDefinitionsResult {
    attributesDefinitions?: AttributeDefinitionResult[] | undefined;
}

export interface GetCategoryResult {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    groupId?: number | undefined;
    createdAt?: Date;
    modifiedAt?: Date;
    attributes?: AttributeDefinitionResult[] | undefined;
}

export interface GetGroupResult {
    id?: number;
    name?: string | undefined;
    photo?: string | undefined;
    icon?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    createdAt?: Date;
    modifiedAt?: Date;
    attributes?: AttributeDefinitionResult[] | undefined;
}

export interface GetMenuCategory {
    id?: number;
    name?: string | undefined;
    subCategories?: GetMenuSubCategory[] | undefined;
}

export interface GetMenuGroup {
    id?: number;
    name?: string | undefined;
    photo?: string | undefined;
    icon?: string | undefined;
    categories?: GetMenuCategory[] | undefined;
}

export interface GetMenuResult {
    groups?: GetMenuGroup[] | undefined;
}

export interface GetMenuSubCategory {
    id?: number;
    name?: string | undefined;
}

export interface GetProductCatalogResult {
    products?: GetProductCatalogResultProduct[] | undefined;
    pageCount?: number;
    pageSize?: number;
    page?: number;
}

export interface GetProductCatalogResultProduct {
    id?: string;
    name?: string | undefined;
    price?: Money;
    photo?: string | undefined;
    status?: ProductStatus;
    stockQuantity?: number;
}

export interface GetProductResult {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    amount?: number;
    currency?: string | undefined;
    photos?: string[] | undefined;
    status?: ProductStatus;
    groupId?: number | undefined;
    categoryId?: number | undefined;
    subCategoryId?: number | undefined;
    active?: boolean;
    stockQuantity?: number;
    attributes?: ProductAttributeResult[] | undefined;
}

export interface GetSearchProductsResult {
    products?: GetSearchProductsResultProduct[] | undefined;
    pageCount?: number;
    pageSize?: number;
    page?: number;
}

export interface GetSearchProductsResultProduct {
    id?: string;
    name?: string | undefined;
    amount?: number;
    currency?: string | undefined;
    photo?: string | undefined;
    status?: ProductStatus;
    averageOpinionRating?: number;
    opinionCount?: number;
    attributes?: ProductAttributeResult[] | undefined;
}

export interface GetSubCategoryResult {
    id?: number;
    name?: string | undefined;
    description?: string | undefined;
    active?: boolean;
    displayOrder?: number;
    categoryId?: number | undefined;
    createdAt?: Date;
    modifiedAt?: Date;
    attributes?: AttributeDefinitionResult[] | undefined;
}

export interface Money {
    amount?: number;
    currency?: string | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export interface ProductAttributeResult {
    id?: string;
    name?: string | undefined;
    type?: AttributeType;
    value?: string | undefined;
    isPrimary?: boolean;
}

export enum ProductStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
}