# fly.toml app configuration file generated for electro-api-rest-new on 2024-12-22T10:22:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'electro-api-rest-new'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
